language: php
php:
  - '7'
  - 5.6
  - 5.5
install:
  - composer self-update
  - composer install
  - touch lando
  - chmod +x lando
  - mkdir -p /usr/local/bin
  - sudo mv lando /usr/local/bin

script:
  - vendor/bin/robo test
